export const allItems = [
  { _id: 100, title: "All Categories" },
  { _id: 101, title: "Alexa Skills" },
  { _id: 102, title: "Amazon Devices" },
  { _id: 103, title: "Amazon Fashion" },
  { _id: 104, title: "Amazon Pharmacy" },
  { _id: 105, title: "Appliances" },
  { _id: 106, title: "Apps & Games" },
  { _id: 107, title: "Baby" },
  { _id: 108, title: "Beauty" },
  { _id: 109, title: "Books" },
  { _id: 110, title: "Car & Motorbike" },
  { _id: 111, title: "Clothing & Accessories" },
  { _id: 112, title: "Collectibles" },
  { _id: 113, title: "Computers & Accessories" },
  { _id: 114, title: "Electronics" },
  { _id: 115, title: "Furniture" },
  { _id: 116, title: "Garden & Outdoors" },
  { _id: 117, title: "Gift Cards" },
  { _id: 118, title: "Grocery & Gourmet Foods" },
  { _id: 119, title: "Health & Personal Care" },
  { _id: 120, title: "Home & Kitchen" },
  { _id: 121, title: "Industrial & Scientific" },
  { _id: 122, title: "Jewellery" },
  { _id: 123, title: "Kindle Store" },
  { _id: 124, title: "Luggage & Bags" },
  { _id: 125, title: "Luxury Beauty" },
  { _id: 126, title: "Movies & TV Shows" },
  { _id: 127, title: "Music" },
  { _id: 128, title: "Musical Instruments" },
  { _id: 129, title: "Office Products" },
  { _id: 130, title: "Pet Supplies" },
  { _id: 131, title: "Prime Video" },
  { _id: 132, title: "Shoes & Handbags" },
  { _id: 133, title: "Software" },
  { _id: 134, title: "Sports, Fitness & Outdoors" },
  { _id: 135, title: "Subscribe & Save" },
  { _id: 136, title: "Tools & Home Improvement" },
  { _id: 137, title: "Toys & Games" },
  { _id: 138, title: "Under ₹500" },
  { _id: 139, title: "Video Games" },
  { _id: 140, title: "Watches" },
];

export const middleList = [
  {
    _id: 2221,
    title: "Get to Know Us",
    listItems: [
      {
        _id: "001",
        listData: [
          "Careers",
          "Blog",
          "About Amazon",
          "Investor Relations",
          "Amazon Devices",
          "Amazon Tours",
          "Press & Media",
        ],
      },
    ],
  },
  {
    _id: 2222,
    title: "Make Money with Us",
    listItems: [
      {
        _id: "002",
        listData: [
          "Sell products on Amazon",
          "Sell apps on Amazon",
          "Become an Affiliate",
          "Advertise Your Products",
          "Self-Publish with Us",
          "Host an Amazon Hub",
        ],
      },
    ],
  },
  {
    _id: 2223,
    title: "Amazon Payment Products",
    listItems: [
      {
        _id: "003",
        listData: [
          "Amazon Rewards Visa Signature Cards",
          "Amazon Store Card",
          "Amazon Secured Card",
          "Amazon Business Card",
          "Amazon Business Line of Credit",
          "Shop with Points",
          "Credit Card Marketplace",
          "Reload Your Balance",
          "Amazon Currency Converter",
        ],
      },
    ],
  },
  {
    _id: 2224,
    title: "Let Us Help You",
    listItems: [
      {
        _id: "004",
        listData: [
          "Amazon and COVID-19",
          "Your Account",
          "Your Orders",
          "Shipping Rates & Policies",
          "Amazon Prime",
          "Returns & Replacements",
          "Manage Your Content and Devices",
          "Amazon Assistant",
          "Help",
        ],
      },
    ],
  },
];
